set(FUNKIN_SOURCES
    Funkin/main.cpp
    Funkin/FunkinState.cpp
    Funkin/game/GameConfig.cpp
    Funkin/game/Section.cpp
    Funkin/play/character/Character.cpp
    Funkin/play/character/CharacterManager.cpp
    Funkin/play/components/HealthBar.cpp
    Funkin/play/components/HealthIcon.cpp
    Funkin/play/components/PopUpStuff.cpp
    Funkin/play/input/Controls.cpp
    Funkin/play/notes/NoteHitHandler.cpp
    Funkin/play/notes/NoteManager.cpp
    Funkin/play/notes/NoteSprite.cpp
    Funkin/play/notes/NoteUpdateHandler.cpp
    Funkin/play/notes/Strumline.cpp
    Funkin/play/scoring/Highscore.cpp
    Funkin/play/scoring/Scoring.cpp
    Funkin/play/song/Conductor.cpp
    Funkin/play/song/Song.cpp
    Funkin/play/song/SongLoader.cpp
    Funkin/play/stage/Stage.cpp
    Funkin/play/CameraManager.cpp
    Funkin/play/Countdown.cpp
    Funkin/play/GameOverSubState.cpp
    Funkin/play/GameplayManager.cpp
    Funkin/play/PauseHandler.cpp
    Funkin/play/PauseSubState.cpp
    Funkin/play/PlayState.cpp
    Funkin/play/PlayStateRenderer.cpp
    Funkin/scripting/Script.cpp
    Funkin/scripting/ScriptAPI.cpp
    Funkin/scripting/ScriptManager.cpp
    Funkin/ui/components/Alphabet.cpp
    Funkin/ui/components/AtlasMenuItem.cpp
    Funkin/ui/components/CheckBox.cpp
    Funkin/ui/components/MenuCharacter.cpp
    Funkin/ui/components/MenuItem.cpp
    Funkin/ui/freeplay/Capsule.cpp
    Funkin/ui/freeplay/DigitDisplay.cpp
    Funkin/ui/CreditsState.cpp
    Funkin/ui/MainMenuState.cpp
    Funkin/ui/NewFreeplayState.cpp
    Funkin/ui/OptionsState.cpp
    Funkin/ui/StoryMenuState.cpp
    Funkin/ui/TitleState.cpp
    lib/tinyxml2/tinyxml2.cpp
    lib/flixel/addons/transition/FlxTransitionEffect.cpp
    lib/flixel/addons/FlxBackdrop.cpp
    lib/flixel/animation/FlxAnimationController.cpp
    lib/flixel/effects/FlxFlicker.cpp
    lib/flixel/graphics/frames/FlxAtlasFrames.cpp
    lib/flixel/input/FlxGamepad.cpp
    lib/flixel/sound/FlxSound.cpp
    lib/flixel/sound/FlxSoundGroup.cpp
    lib/flixel/text/FlxBitmapText.cpp
    lib/flixel/text/FlxText.cpp
    lib/flixel/tweens/FlxTween.cpp
    lib/flixel/util/FlxTimer.cpp
    lib/flixel/FlxBasic.cpp
    lib/flixel/FlxCamera.cpp
    lib/flixel/FlxG.cpp
    lib/flixel/FlxGame.cpp
    lib/flixel/FlxObject.cpp
    lib/flixel/FlxSprite.cpp
    lib/flixel/FlxState.cpp
    lib/flixel/FlxSubState.cpp
)
